# NoShow - Feature selection R

In [2]:
library(dplyr)
library (mechkar)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union


Warning message:
"package 'mechkar' was built under R version 3.6.3"

In [136]:
df <- read.csv("c:/Users/Mayer/Documents/DataScience/project/Noshows/NoShowClusters.csv",row.names = NULL)
df <- df[2:65]
summary(df)

  Client_Code       Booking_Date      sunday            monday
 BROS01 :  27   2018-05-31:  42   Min.   :0.00000   Min.   :0.0000000
 WONM02 :  27   2018-06-02:  41   1st Qu.:0.00000   1st Qu.:0.0000000
 SIRM01 :  24   2018-05-29:  38   Median :0.00000   Median :0.0000000
 COLG01 :  23   2018-06-15:  34   Mean   :0.02976   Mean   :0.0004579
 KUKK01 :  23   2018-07-20:  34   3rd Qu.:0.00000   3rd Qu.:0.0000000
 NELT01 :  21   2018-07-27:  33   Max.   :1.00000   Max.   :1.0000000
 (Other):2039   (Other)   :1962
   wednesday         thursday          friday          saturday
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.0000   Median :0.0000   Median :0.0000   Median :0.0000
 Mean   :0.1456   Mean   :0.2083   Mean   :0.2152   Mean   :0.1969
 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.0000
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000

  time_booked   cancel_days     NoShow        service_CAL
 Min.   : 480   0   : 134   Min.   :0.0000   Min.   :0.000000
 1st Qu.: 660   1   :  36   1st Qu.:0.0000   1st Qu.:0.000000
 Median : 800   2   :  18   Median :0.0000   Median :0.000000
 Mean   : 808   3   :  14   Mean   :0.0783   Mean   :0.002747
 3rd Qu.: 960   4-7 :  31   3rd Qu.:0.0000   3rd Qu.:0.000000
 Max.   :1170   8+  :  41   Max.   :1.0000   Max.   :1.000000
                miss:1910
  service_CALC      service_CAS         service_CBAL     service_CCAMO
 Min.   :0.00000   Min.   :0.0000000   Min.   :0.00000   Min.   :0.0000
 1st Qu.:0.00000   1st Qu.:0.0000000   1st Qu.:0.00000   1st Qu.:0.0000
 Median :0.00000   Median :0.0000000   Median :0.00000   Median :0.0000
 Mean   :0.01832   Mean   :0.0004579   Mean   :0.01099   Mean   :0.0087
 3rd Qu.:0.00000   3rd Qu.:0.0000000   3rd Qu.:0.00000   3rd Qu.:0.0000
 Max.   :1.00000   Max.   :1.0000000   Max.   :1.00000   Max.   :1.0000

  service_CCO         service_CDPB      service_CFC      service_CHLFH
 Min.   :0.0000000   Min.   :0.00000   Min.   :0.00000   Min.   :0.00000
 1st Qu.:0.0000000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000
 Median :0.0000000   Median :0.00000   Median :0.00000   Median :0.00000
 Mean   :0.0009158   Mean   :0.00641   Mean   :0.03022   Mean   :0.00641
 3rd Qu.:0.0000000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000
 Max.   :1.0000000   Max.   :1.00000   Max.   :1.00000   Max.   :1.00000

 service_CHLFHC      service_CHLHH      service_CHLHHC     service_CHLPHC
 Min.   :0.0000000   Min.   :0.000000   Min.   :0.000000   Min.   :0.000000
 1st Qu.:0.0000000   1st Qu.:0.000000   1st Qu.:0.000000   1st Qu.:0.000000
 Median :0.0000000   Median :0.000000   Median :0.000000   Median :0.000000
 Mean   :0.0004579   Mean   :0.002747   Mean   :0.001374   Mean   :0.008242
 3rd Qu.:0.0000000   3rd Qu.:0.000000   3rd Qu.:0.000000   3rd Qu.:0.000000
 Max.   :1.0000000   Max.   :1.000000   Max.   :1.000000   Max.   :1.000000

 service_CHLPL      service_CMT        service_CON        service_CT
 Min.   :0.00000   Min.   :0.000000   Min.   :0.00000   Min.   :0.000000
 1st Qu.:0.00000   1st Qu.:0.000000   1st Qu.:0.00000   1st Qu.:0.000000
 Median :0.00000   Median :0.000000   Median :0.00000   Median :0.000000
 Mean   :0.02381   Mean   :0.005495   Mean   :0.04258   Mean   :0.004579
 3rd Qu.:0.00000   3rd Qu.:0.000000   3rd Qu.:0.00000   3rd Qu.:0.000000
 Max.   :1.00000   Max.   :1.000000   Max.   :1.00000   Max.   :1.000000

  service_CTU       service_EXT   service_FF  service_FRI
 Min.   :0.00000   Min.   :0    Min.   :0    Min.   :0.000000
 1st Qu.:0.00000   1st Qu.:0    1st Qu.:0    1st Qu.:0.000000
 Median :0.00000   Median :0    Median :0    Median :0.000000
 Mean   :0.04991   Mean   :0    Mean   :0    Mean   :0.003663
 3rd Qu.:0.00000   3rd Qu.:0    3rd Qu.:0    3rd Qu.:0.000000
 Max.   :1.00000   Max.   :0    Max.   :0    Max.   :1.000000

  service_MISC       service_NECK  service_SBD      service_SBD5
 Min.   :0.000000   Min.   :0     Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.000000   1st Qu.:0     1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.000000   Median :0     Median :0.0000   Median :0.0000
 Mean   :0.001374   Mean   :0     Mean   :0.1754   Mean   :0.0087
 3rd Qu.:0.000000   3rd Qu.:0     3rd Qu.:0.0000   3rd Qu.:0.0000
 Max.   :1.000000   Max.   :0     Max.   :1.0000   Max.   :1.0000

  service_SDUD       service_SHCC       service_SHCM     service_SHCW
 Min.   :0.000000   Min.   :0.000000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.000000   1st Qu.:0.000000   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.000000   Median :0.000000   Median :0.0000   Median :0.0000
 Mean   :0.004121   Mean   :0.007326   Mean   :0.2138   Mean   :0.3603
 3rd Qu.:0.000000   3rd Qu.:0.000000   3rd Qu.:0.0000   3rd Qu.:1.0000
 Max.   :1.000000   Max.   :1.000000   Max.   :1.0000   Max.   :1.0000

 service_SMARTBOND   service_SMO        service_SSUD  staff_BECKY
 Min.   :0.000000   Min.   :0.000000   Min.   :0     Min.   :0.0000
 1st Qu.:0.000000   1st Qu.:0.000000   1st Qu.:0     1st Qu.:0.0000
 Median :0.000000   Median :0.000000   Median :0     Median :0.0000
 Mean   :0.004579   Mean   :0.001374   Mean   :0     Mean   :0.2363
 3rd Qu.:0.000000   3rd Qu.:0.000000   3rd Qu.:0     3rd Qu.:0.0000
 Max.   :1.000000   Max.   :1.000000   Max.   :0     Max.   :1.0000

  staff_HOUSE          staff_JJ       staff_JOANNE     staff_KELLY
 Min.   :0.000000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000
 1st Qu.:0.000000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000
 Median :0.000000   Median :0.0000   Median :0.0000   Median :0.0000
 Mean   :0.009615   Mean   :0.3755   Mean   :0.1378   Mean   :0.1474
 3rd Qu.:0.000000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.0000
 Max.   :1.000000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000

  staff_SINEAD     Canceled_By_BECKY Canceled_By_HOUSE Canceled_By_JJ
 Min.   :0.00000   Min.   :0.00000   Min.   :0         Min.   :0.00000
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0         1st Qu.:0.00000
 Median :0.00000   Median :0.00000   Median :0         Median :0.00000
 Mean   :0.09295   Mean   :0.01328   Mean   :0         Mean   :0.04258
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0         3rd Qu.:0.00000
 Max.   :1.00000   Max.   :1.00000   Max.   :0         Max.   :1.00000

 Canceled_By_JOANNE Canceled_By_KELLY Canceled_By_SINEAD quantity
 Min.   :0.000000   Min.   :0.00000   Min.   :0.000000   0   :   1
 1st Qu.:0.000000   1st Qu.:0.00000   1st Qu.:0.000000   1   :1111
 Median :0.000000   Median :0.00000   Median :0.000000   2   : 460
 Mean   :0.007784   Mean   :0.01465   Mean   :0.007326   3   :  99
 3rd Qu.:0.000000   3rd Qu.:0.00000   3rd Qu.:0.000000   4   :  24
 Max.   :1.000000   Max.   :1.00000   Max.   :1.000000   5-7 :  19
                                                         miss: 470
     amount                avg_receipt  avg_quantity total_cancel12
 Min.   :0.000   0               :844   0   :869     Min.   :0.0000
 1st Qu.:3.829   174.933333333333:424   1   :435     1st Qu.:0.0000
 Median :4.263   30              :420   1.1 :435     Median :0.0000
 Mean   :3.983   67.2222222222222:417   3   :434     Mean   :0.7035
 3rd Qu.:4.710   miss            : 79   miss: 11     3rd Qu.:1.0986
 Max.   :5.950                                       Max.   :4.5109

    hclust3         hclust4        Mclust3         Mclust4
 Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000
 1st Qu.:1.000   1st Qu.:1.00   1st Qu.:1.000   1st Qu.:1.000
 Median :2.000   Median :2.00   Median :2.000   Median :2.000
 Mean   :1.916   Mean   :2.24   Mean   :1.897   Mean   :2.318
 3rd Qu.:3.000   3rd Qu.:3.00   3rd Qu.:3.000   3rd Qu.:3.000
 Max.   :3.000   Max.   :4.00   Max.   :3.000   Max.   :4.000

In [137]:
#rearrange df so NoShow willl be first
df <- df[,c(11,1:10,12:64)]
head(df)

  NoShow Client_Code Booking_Date sunday monday wednesday thursday friday
1 1      WXATNI      2018-04-13   0      0      0         0        1
2 0      Q4NPGP      2018-04-13   0      0      0         0        1
3 0      .L01        2018-05-23   0      0      1         0        0
4 0      .L01        2018-05-23   0      0      1         0        0
5 0      .L01        2018-06-27   0      0      1         0        0
6 0      .L01        2018-08-22   0      0      1         0        0
  saturday time_booked ... Canceled_By_SINEAD quantity amount
1 0         720        ... 0                  miss     5.382199
2 0        1080        ... 0                  miss     4.418841
3 0         640        ... 0                  2        5.572154
4 0         790        ... 0                  2        5.572154
5 0         780        ... 0                  miss     3.583519
6 0         660        ... 0                  miss     4.418841
  avg_receipt      avg_quantity total_cancel12 hclust3 hclust4 Mclust3 Mclust4
1 0                0            0.0000000      1       1       1       4
2 0                0            0.0000000      2       2       3       1
3 30               1            0.6931472      1       1       1       2
4 67.2222222222222 1.1          0.6931472      3       3       2       4
5 miss             3            0.6931472      3       3       2       4
6 miss             0            0.6931472      1       1       1       2

In [119]:
#table of types
TypeTab <- NULL

In [126]:
TypeTab <- cbind(Index=c(1:64),Type=sapply(df[,1:64],class))
TypeTab

                   Index Type
NoShow             1     factor
Client_Code        2     factor
Booking_Date       3     factor
sunday             4     factor
monday             5     factor
wednesday          6     factor
thursday           7     factor
friday             8     factor
saturday           9     factor
time_booked        10    integer
cancel_days        11    factor
service_CAL        12    factor
service_CALC       13    factor
service_CAS        14    factor
service_CBAL       15    factor
service_CCAMO      16    factor
service_CCO        17    factor
service_CDPB       18    factor
service_CFC        19    factor
service_CHLFH      20    factor
service_CHLFHC     21    factor
service_CHLHH      22    factor
service_CHLHHC     23    factor
service_CHLPHC     24    factor
service_CHLPL      25    factor
service_CMT        26    factor
service_CON        27    factor
service_CT         28    factor
service_CTU        29    factor
service_EXT        30    factor
...                ...   ...
service_SBD        35    factor
service_SBD5       36    factor
service_SDUD       37    factor
service_SHCC       38    factor
service_SHCM       39    factor
service_SHCW       40    factor
service_SMARTBOND  41    factor
service_SMO        42    factor
service_SSUD       43    factor
staff_BECKY        44    factor
staff_HOUSE        45    factor
staff_JJ           46    factor
staff_JOANNE       47    factor
staff_KELLY        48    factor
staff_SINEAD       49    factor
Canceled_By_BECKY  50    factor
Canceled_By_HOUSE  51    factor
Canceled_By_JJ     52    factor
Canceled_By_JOANNE 53    factor
Canceled_By_KELLY  54    factor
Canceled_By_SINEAD 55    factor
quantity           56    factor
amount             57    numeric
avg_receipt        58    factor
avg_quantity       59    factor
total_cancel12     60    numeric
hclust3            61    factor
hclust4            62    factor
Mclust3            63    factor
Mclust4            64    factor

In [125]:
data$NoShow             <-as.factor(data$NoShow)
data$sunday             <-as.factor(data$sunday)
data$monday             <-as.factor(data$monday)
data$wednesday          <-as.factor(data$wednesday)
data$thursday           <-as.factor(data$thursday)
data$friday             <-as.factor(data$friday) 
data$saturday           <-as.factor(data$saturday)
data$cancel_days_1      <-as.factor(data$cancel_days_1)
data$cancel_days_2      <-as.factor(data$cancel_days_2)
data$cancel_days_3      <-as.factor(data$cancel_days_3)
data$cancel_days_4      <-as.factor(data$cancel_days_4)
data$cancel_days_5      <-as.factor(data$cancel_days_5)
data$cancel_days_6      <-as.factor(data$cancel_days_6)
data$cancel_days_7      <-as.factor(data$cancel_days_7)
data$service_CAL        <-as.factor(data$service_CAL)
data$service_CALC       <-as.factor(data$service_CALC)
data$service_CAS        <-as.factor(data$service_CAS)
data$service_CBAL       <-as.factor(data$service_CBAL)
data$service_CCAMO      <-as.factor(data$service_CCAMO)
data$service_CCO        <-as.factor(data$service_CCO)
data$service_CDPB       <-as.factor(data$service_CDPB)
data$service_CFC        <-as.factor(data$service_CFC)
data$service_CHLFH      <-as.factor(data$service_CHLFH)
data$service_CHLFHC     <-as.factor(data$service_CHLFHC)
data$service_CHLHH      <-as.factor(data$service_CHLHH)
data$service_CHLHHC     <-as.factor(data$service_CHLHHC)
data$service_CHLPHC     <-as.factor(data$service_CHLPHC)
data$service_CHLPL      <-as.factor(data$service_CHLPL)
data$service_CMT        <-as.factor(data$service_CMT)
data$service_CON        <-as.factor(data$service_CON)
data$service_CT         <-as.factor(data$service_CT)
data$service_CTU        <-as.factor(data$service_CTU)
data$service_EXT        <-as.factor(data$service_EXT)
data$service_FF         <-as.factor(data$service_FF)
data$service_FRI        <-as.factor(data$service_FRI)
data$service_MISC       <-as.factor(data$service_MISC)
data$service_NECK       <-as.factor(data$service_NECK)
data$service_SBD        <-as.factor(data$service_SBD)
data$service_SBD5       <-as.factor(data$service_SBD5)
data$service_SDUD       <-as.factor(data$service_SDUD)
data$service_SHCC       <-as.factor(data$service_SHCC)
data$service_SHCM       <-as.factor(data$service_SHCM)
data$service_SHCW       <-as.factor(data$service_SHCW)
data$service_SMARTBOND  <-as.factor(data$service_SMARTBOND)
data$service_SMO        <-as.factor(data$service_SMO)
data$service_SSUD       <-as.factor(data$service_SSUD)
data$staff_BECKY        <-as.factor(data$staff_BECKY)
data$staff_HOUSE        <-as.factor(data$staff_HOUSE)
data$staff_JJ           <-as.factor(data$staff_JJ)
data$staff_JOANNE       <-as.factor(data$staff_JOANNE)
data$staff_KELLY        <-as.factor(data$staff_KELLY)
data$staff_SINEAD       <-as.factor(data$staff_SINEAD)
data$Canceled_By_BECKY  <-as.factor(data$Canceled_By_BECKY)
data$Canceled_By_HOUSE  <-as.factor(data$Canceled_By_HOUSE)
data$Canceled_By_JJ     <-as.factor(data$Canceled_By_JJ)
data$Canceled_By_JOANNE <-as.factor(data$Canceled_By_JOANNE)
data$Canceled_By_KELLY  <-as.factor(data$Canceled_By_KELLY)
data$Canceled_By_SINEAD <-as.factor(data$Canceled_By_SINEAD)
data$quantity_1         <-as.factor(data$quantity_1)
data$quantity_2         <-as.factor(data$quantity_2)
data$quantity_3         <-as.factor(data$quantity_3)
data$quantity_4         <-as.factor(data$quantity_4)
data$quantity_5         <-as.factor(data$quantity_5)
data$quantity_6         <-as.factor(data$quantity_6)
data$quantity_7         <-as.factor(data$quantity_7)
data$avg_receipt_1      <-as.factor(data$avg_receipt_1)
data$avg_receipt_2      <-as.factor(data$avg_receipt_2)
data$avg_receipt_3      <-as.factor(data$avg_receipt_3)
data$avg_receipt_4      <-as.factor(data$avg_receipt_4)
data$avg_receipt_5      <-as.factor(data$avg_receipt_5)
data$avg_quantity_1     <-as.factor(data$avg_quantity_1)
data$avg_quantity_2     <-as.factor(data$avg_quantity_2)
data$avg_quantity_3     <-as.factor(data$avg_quantity_3)
data$avg_quantity_4     <-as.factor(data$avg_quantity_4)
data$avg_quantity_5     <-as.factor(data$avg_quantity_5)
data$hclust3            <-as.factor(data$hclust3)
data$hclust4            <-as.factor(data$hclust4)
data$Mclust3            <-as.factor(data$Mclust3)
data$Mclust4            <-as.factor(data$Mclust4)

In [133]:
summary(df)

 NoShow    Client_Code       Booking_Date  sunday   monday   wednesday thursday
 0:2013   BROS01 :  27   2018-05-31:  42   0:2119   0:2183   0:1866    0:1729
 1: 171   WONM02 :  27   2018-06-02:  41   1:  65   1:   1   1: 318    1: 455
          SIRM01 :  24   2018-05-29:  38
          COLG01 :  23   2018-06-15:  34
          KUKK01 :  23   2018-07-20:  34
          NELT01 :  21   2018-07-27:  33
          (Other):2039   (Other)   :1962
 friday   saturday  time_booked   cancel_days service_CAL service_CALC
 0:1714   0:1754   Min.   : 480   0   : 134   0:2178      0:2144
 1: 470   1: 430   1st Qu.: 660   1   :  36   1:   6      1:  40
                   Median : 800   2   :  18
                   Mean   : 808   3   :  14
                   3rd Qu.: 960   4-7 :  31
                   Max.   :1170   8+  :  41
                                  miss:1910
 service_CAS service_CBAL service_CCAMO service_CCO service_CDPB service_CFC
 0:2183      0:2160       0:2165        0:2182      0:2170       0:2118
 1:   1      1:  24       1:  19        1:   2      1:  14       1:  66





 service_CHLFH service_CHLFHC service_CHLHH service_CHLHHC service_CHLPHC
 0:2170        0:2183         0:2178        0:2181         0:2166
 1:  14        1:   1         1:   6        1:   3         1:  18





 service_CHLPL service_CMT service_CON service_CT service_CTU service_EXT
 0:2132        0:2172      0:2091      0:2174     0:2075      0:2184
 1:  52        1:  12      1:  93      1:  10     1: 109





 service_FF service_FRI service_MISC service_NECK service_SBD service_SBD5
 0:2184     0:2176      0:2181       0:2184       0:1801      0:2165
            1:   8      1:   3                    1: 383      1:  19





 service_SDUD service_SHCC service_SHCM service_SHCW service_SMARTBOND
 0:2175       0:2168       0:1717       0:1397       0:2174
 1:   9       1:  16       1: 467       1: 787       1:  10





 service_SMO service_SSUD staff_BECKY staff_HOUSE staff_JJ staff_JOANNE
 0:2181      0:2184       0:1668      0:2163      0:1364   0:1883
 1:   3                   1: 516      1:  21      1: 820   1: 301





 staff_KELLY staff_SINEAD Canceled_By_BECKY Canceled_By_HOUSE Canceled_By_JJ
 0:1862      0:1981       0:2155            0:2184            0:2091
 1: 322      1: 203       1:  29                              1:  93





 Canceled_By_JOANNE Canceled_By_KELLY Canceled_By_SINEAD quantity
 0:2167             0:2152            0:2168             0   :   1
 1:  17             1:  32            1:  16             1   :1111
                                                         2   : 460
                                                         3   :  99
                                                         4   :  24
                                                         5-7 :  19
                                                         miss: 470
     amount                avg_receipt  avg_quantity total_cancel12   hclust3
 Min.   :0.000   0               :844   0   :869     Min.   :0.0000   1:988
 1st Qu.:3.829   174.933333333333:424   1   :435     1st Qu.:0.0000   2:391
 Median :4.263   30              :420   1.1 :435     Median :0.0000   3:805
 Mean   :3.983   67.2222222222222:417   3   :434     Mean   :0.7035
 3rd Qu.:4.710   miss            : 79   miss: 11     3rd Qu.:1.0986
 Max.   :5.950                                       Max.   :4.5109

 hclust4 Mclust3 Mclust4
 1:752   1:855   1:594
 2:391   2:700   2:699
 3:805   3:629   3:493
 4:236           4:398

In [235]:
### Table of Variables selection
### Variable, Univarable, Lasso, RandomForest,Gradient Boosting,SVM,sum

VarSel <- NULL

In [236]:
VarSel <- data.frame(cbind(VarSel,Index=c(2:64),Variable=names(df[,2:64])))
VarSel

    Index Variable
1   2     Client_Code
2   3     Booking_Date
3   4     sunday
4   5     monday
5   6     wednesday
6   7     thursday
7   8     friday
8   9     saturday
9   10    time_booked
10  11    cancel_days
11  12    service_CAL
12  13    service_CALC
13  14    service_CAS
14  15    service_CBAL
15  16    service_CCAMO
16  17    service_CCO
17  18    service_CDPB
18  19    service_CFC
19  20    service_CHLFH
20  21    service_CHLFHC
21  22    service_CHLHH
22  23    service_CHLHHC
23  24    service_CHLPHC
24  25    service_CHLPL
25  26    service_CMT
26  27    service_CON
27  28    service_CT
28  29    service_CTU
29  30    service_EXT
30  31    service_FF
... ...   ...
34  35    service_SBD
35  36    service_SBD5
36  37    service_SDUD
37  38    service_SHCC
38  39    service_SHCM
39  40    service_SHCW
40  41    service_SMARTBOND
41  42    service_SMO
42  43    service_SSUD
43  44    staff_BECKY
44  45    staff_HOUSE
45  46    staff_JJ
46  47    staff_JOANNE
47  48    staff_KELLY
48  49    staff_SINEAD
49  50    Canceled_By_BECKY
50  51    Canceled_By_HOUSE
51  52    Canceled_By_JJ
52  53    Canceled_By_JOANNE
53  54    Canceled_By_KELLY
54  55    Canceled_By_SINEAD
55  56    quantity
56  57    amount
57  58    avg_receipt
58  59    avg_quantity
59  60    total_cancel12
60  61    hclust3
61  62    hclust4
62  63    Mclust3
63  64    Mclust4

## Univariable Analysis

In [138]:
vn <- setdiff(names(df),"NoShow")

In [164]:
tab1 <- Table1(data=df,x=vn, y='NoShow',messages=FALSE)
tab1

Warning message in Table1(data = df, x = vn, y = "NoShow", messages = FALSE):
"The following variables have unique values and will not be included in the analysis: service_EXTThe following variables have unique values and will not be included in the analysis: service_FFThe following variables have unique values and will not be included in the analysis: service_NECKThe following variables have unique values and will not be included in the analysis: service_SSUDThe following variables have unique values and will not be included in the analysis: Canceled_By_HOUSE"

  |======================================================================| 100%

Warning message in `[<-.factor`(`*tmp*`, iseq, value = "0"):
"invalid factor level, NA generated"
Warning message:
"Column `Del` joining character vector and factor, coercing into character vector"
Warning message:
"Column `V1` joining character vector and factor, coercing into character vector"
Warning message:
"Column `V2` joining character vector and factor, coercing into character vector"
Warning message:
"Column `n` joining character vector and factor, coercing into character vector"

  |======================================================================| 100%

Warning message in `[<-.factor`(`*tmp*`, iseq, value = "1"):
"invalid factor level, NA generated"
Warning message:
"Column `Del` joining character vector and factor, coercing into character vector"
Warning message:
"Column `V1` joining character vector and factor, coercing into character vector"
Warning message:
"Column `V2` joining character vector and factor, coercing into character vector"
Warning message:
"Column `n` joining character vector and factor, coercing into character vector"

  |===================================================================== |  98%

Warning message:
"Column `V1` joining character vector and factor, coercing into character vector"
Warning message:
"Column `n` joining character vector and factor, coercing into character vector"

     V1                 V2               Pop           0
1    Individuals        n                2184          2013
2    Client_Code        .L01             4 (0.2%)      4 (0.2%)
3    Client_Code        ?A01             5 (0.2%)      4 (0.2%)
4    Client_Code        ABL*01           4 (0.2%)      3 (0.1%)
5    Client_Code        ABLD01           1 (0.0%)      1 (0.0%)
6    Client_Code        ADAP01           2 (0.1%)      2 (0.1%)
7    Client_Code        AGOE01           1 (0.0%)      1 (0.0%)
8    Client_Code        AINM01           2 (0.1%)      2 (0.1%)
9    Client_Code        AITS01           1 (0.0%)      1 (0.0%)
10   Client_Code        ALCV01           5 (0.2%)      4 (0.2%)
11   Client_Code        ALIA01           3 (0.1%)      3 (0.1%)
12   Client_Code        ALIR01           1 (0.0%)      1 (0.0%)
13   Client_Code        ALIR02           1 (0.0%)      1 (0.0%)
14   Client_Code        ALLM01           2 (0.1%)      2 (0.1%)
15   Client_Code        ALVJ01           2 (0.1%)      2 (0.1%)
16   Client_Code        ALZR01           1 (0.0%)      1 (0.0%)
17   Client_Code        AMAB01           2 (0.1%)      1 (0.0%)
18   Client_Code        AMAK01           1 (0.0%)      1 (0.0%)
19   Client_Code        ANDE01           1 (0.0%)      1 (0.0%)
20   Client_Code        ANDE03           1 (0.0%)      1 (0.0%)
21   Client_Code        ANDJ01           4 (0.2%)      4 (0.2%)
22   Client_Code        ANDM01           1 (0.0%)      1 (0.0%)
23   Client_Code        ANDN01           1 (0.0%)      1 (0.0%)
24   Client_Code        APPS01           2 (0.1%)      1 (0.0%)
25   Client_Code        APTM01           6 (0.3%)      5 (0.2%)
26   Client_Code        ARAI01           1 (0.0%)      1 (0.0%)
27   Client_Code        ARBA01           1 (0.0%)      1 (0.0%)
28   Client_Code        ARMG01           1 (0.0%)      1 (0.0%)
29   Client_Code        ARRM01           12 (0.5%)     12 (0.6%)
30   Client_Code        ASIS01           2 (0.1%)      1 (0.0%)
...  ...                ...              ...           ...
1083 Canceled_By_SINEAD Median (IQR)     0.0 (0.0-0.0) 0.0 (0.0-0.0)
1084 quantity           0                1 (0.0%)      1 (0.0%)
1085 quantity           1                1,111 (50.9%) 1,087 (54.0%)
1086 quantity           2                460 (21.1%)   457 (22.7%)
1087 quantity           3                99 (4.5%)     98 (4.9%)
1088 quantity           4                24 (1.1%)     24 (1.2%)
1089 quantity           5-7              19 (0.9%)     18 (0.9%)
1090 quantity           miss             470 (21.5%)   328 (16.3%)
1091 amount             Mean (SD)        4.0 (1.4)     4.0 (1.3)
1092 amount             Median (IQR)     4.3 (3.8-4.7) 4.3 (3.9-4.7)
1093 avg_receipt        0                844 (38.6%)   776 (38.5%)
1094 avg_receipt        174.933333333333 424 (19.4%)   384 (19.1%)
1095 avg_receipt        30               420 (19.2%)   393 (19.5%)
1096 avg_receipt        67.2222222222222 417 (19.1%)   384 (19.1%)
1097 avg_receipt        miss             79 (3.6%)     76 (3.8%)
1098 avg_quantity       0                869 (39.8%)   800 (39.7%)
1099 avg_quantity       1                435 (19.9%)   407 (20.2%)
1100 avg_quantity       1.1              435 (19.9%)   401 (19.9%)
1101 avg_quantity       3                434 (19.9%)   394 (19.6%)
1102 avg_quantity       miss             11 (0.5%)     11 (0.5%)
1103 total_cancel12     Mean (SD)        0.7 (1.1)     0.7 (1.1)
1104 total_cancel12     Median (IQR)     0.0 (0.0-1.1) 0.0 (0.0-1.1)
1105 hclust3            Mean (SD)        1.9 (0.9)     1.9 (0.9)
1106 hclust3            Median (IQR)     2.0 (1.0-3.0) 2.0 (1.0-3.0)
1107 hclust4            Mean (SD)        2.2 (1.0)     2.2 (1.0)
1108 hclust4            Median (IQR)     2.0 (1.0-3.0) 2.0 (1.0-3.0)
1109 Mclust3            Mean (SD)        1.9 (0.8)     1.9 (0.8)
1110 Mclust3            Median (IQR)     2.0 (1.0-3.0) 2.0 (1.0-3.0)
1111 Mclust4            Mean (SD)        2.3 (1.1)     2.3 (1.1)
1112 Mclust4            Median (IQR)     2.0 (1.0-3.0) 2.0 (1.0-3.0)
     1             pval
1    171           NA
2    0 (0.0%)      NA
3    1 (0.6%)      NA
4    1 (0.6%)      NA
5    0 (0.0%)      NA
6    0 (0.0%)      NA
7    0 (0.0%)      NA
8    0 (0.0%)      NA
9    0 (0.0%)      NA
10   1 (0.6%)      NA
11   0 (0.0%)      NA
12   0 (0.0%)      NA
13   0 (0.0%)      NA
14   0 (0.0%)      NA
15   0 (0.0%)      NA
16   0 (0.0%)      NA
17   1 (0.6%)      NA
18   0 (0.0%)      NA
19   0 (0.0%)      NA
20   0 (0.0%)      NA
21   0 (0.0%)      NA
22   0 (0.0%)      NA
23   0 (0.0%)      NA
24   1 (0.6%)      NA
25   1 (0.6%)      NA
26   0 (0.0%)      NA
27   0 (0.0%)      NA
28   0 (0.0%)      NA
29   0 (0.0%)      NA
30   1 (0.6%)      NA
...  ...           ...
1083 0.0 (0.0-0.0) 0.035
1084 0 (0.0%)      NA
1085 24 (14.0%)    0.035
1086 3 (1.8%)      NA
1087 1 (0.6%)      NA
1088 0 (0.0%)      NA
1089 1 (0.6%)      NA
1090 142 (83.0%)   NA
1091 3.5 (1.9)     NA
1092 4.0 (3.4-4.8) 0
1093 68 (39.8%)    NA
1094 40 (23.4%)    0.366
1095 27 (15.8%)    NA
1096 33 (19.3%)    NA
1097 3 (1.8%)      NA
1098 69 (40.4%)    NA
1099 28 (16.4%)    0.366
1100 34 (19.9%)    NA
1101 40 (23.4%)    NA
1102 0 (0.0%)      NA
1103 1.2 (0.7)     NA
1104 1.1 (0.7-1.6) 0
1105 2.0 (0.9)     NA
1106 2.0 (1.0-3.0) 0.462
1107 2.2 (1.0)     NA
1108 2.0 (1.0-3.0) 0.872
1109 2.0 (0.9)     NA
1110 2.0 (1.0-3.0) 0.255
1111 2.2 (1.0)     NA
1112 2.0 (1.0-3.0) 0.092

In [166]:
summary(tab1$pval)

    0 0.001 0.002 0.003  0.01 0.014 0.018 0.028 0.034 0.035 0.041 0.058 0.067
    8     2     1     1     1     1     1     1     1     2     1     1     1
0.083 0.092 0.106 0.138 0.142 0.182 0.183 0.244 0.255 0.281 0.294 0.318 0.351
    2     1     1     1     1     1     2     1     1     1     1     3     1
0.363 0.366 0.409 0.411 0.427 0.462 0.497 0.727 0.788 0.792 0.804  0.82 0.872
    1     2     1     1     1     1     1     1     1     1     1     1     1
 0.92  0.97 0.973  pval  NA's
    1     1     1     0  1056

In [237]:
tab1 <- tab1 %>% filter (pval=='0' | pval=='0.001' | pval=='0.002' | pval=='0.003' | pval=='0.01' | pval=='0.014' | pval=='0.018' | pval=='0.028' | pval=='0.034' | pval=='0.035' | pval=='0.041')
tab1

   V1                 V2           Pop           0             1
1  sunday             Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
2  service_CAL        Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
3  service_CALC       Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
4  service_CBAL       Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
5  service_CHLPHC     Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
6  service_CMT        Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
7  service_CON        Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
8  service_CT         Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
9  service_SBD5       Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
10 service_SDUD       Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
11 service_SHCW       Median (IQR) 0.0 (0.0-1.0) 0.0 (0.0-1.0) 0.0 (0.0-0.0)
12 staff_KELLY        Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
13 Canceled_By_BECKY  Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
14 Canceled_By_JJ     Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-1.0)
15 Canceled_By_JOANNE Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
16 Canceled_By_KELLY  Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
17 Canceled_By_SINEAD Median (IQR) 0.0 (0.0-0.0) 0.0 (0.0-0.0) 0.0 (0.0-0.0)
18 quantity           1            1,111 (50.9%) 1,087 (54.0%) 24 (14.0%)
19 amount             Median (IQR) 4.3 (3.8-4.7) 4.3 (3.9-4.7) 4.0 (3.4-4.8)
20 total_cancel12     Median (IQR) 0.0 (0.0-1.1) 0.0 (0.0-1.1) 1.1 (0.7-1.6)
   pval
1  0.028
2  0.014
3  0.041
4  0.018
5  0
6  0.001
7  0
8  0.002
9  0
10 0.003
11 0
12 0.034
13 0.001
14 0
15 0.01
16 0
17 0.035
18 0.035
19 0
20 0

In [238]:
vn1 <-data.frame(Variable=tab1$V1)
vn1

   Variable
1  sunday
2  service_CAL
3  service_CALC
4  service_CBAL
5  service_CHLPHC
6  service_CMT
7  service_CON
8  service_CT
9  service_SBD5
10 service_SDUD
11 service_SHCW
12 staff_KELLY
13 Canceled_By_BECKY
14 Canceled_By_JJ
15 Canceled_By_JOANNE
16 Canceled_By_KELLY
17 Canceled_By_SINEAD
18 quantity
19 amount
20 total_cancel12

In [245]:
VarSel$Univariable <- 0

In [246]:
VarSel$Univariable <- ifelse((vn1$Variable %in% VarSel$Variable),1,VarSel$Univariable)
VarSel

ERROR: Error in `$<-.data.frame`(`*tmp*`, Univariable, value = c(1, 1, 1, 1, : replacement has 20 rows, data has 63